# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d93445eabe152a497d3ef27ebf25df72b5859d187b6c786761923e9660433f3d853b07f9038a1276b0e23894d4d78956b7076ecbe4bff0e256b121e7698fc4b

test:
  secret_key_base: f6bae9f1375d0179909d13e8e20736d9bae615fa2eeb2b98f589023b16b9e9df447a3334bbbe1bfdb8a106b275bd2227c7de6260702848bdb80e7908c0914b08

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
